Fix for sqlite dataProvider
This change fixes "TypeError: data.find is not a function" from validateData(). Apparently schemaCache returns a string instead of an Array so it has to be parsed first.