Fix for sqlite dataProvider (#27)
* Fix for sqlite dataProvider

This change fixes "TypeError: data.find is not a function" from validateData(). Apparently schemaCache returns a string instead of an Array so it has to be parsed first.

* Update sqlite.js

Forgot update() in previous edit

* Update sqlite.js

Fix: Scoping issues